---
collections:
  - name: ovirt.ovirt
  - name: ansible.posix
  - name: awx.awx
  - name: https://github.com/oracle/oci-ansible-collection.git
    type: git
    version: master
  - name: https://github.com/ansible-collections/community.general.git
    type: git
    version: main
  - name: ovirt.ovirt
