---
collections:
  - name: ovirt.ovirt
  - name: ansible.posix
  - name: awx.awx
  - name: https://github.com/ansible-collections/community.general.git
    type: git
    version: main
  - name: ovirt.ovirt
