
- name: List Compartment Details
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
     - name: List
       oci_access_governance_cp_governance_instance_configuration_facts:
          compartment_id: "ocid1.compartment.oc1..aaaaaaaafjjha3apzlrxkl63ndwgwgvn4caj6swrt7eefmywp7p3dkzcn4ya"
 
