
- name: List Compartment Details
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
     - name: Delete governance_instance
       oci_access_governance_cp_governance_instance:
         governance_instance_id: "ocid1.governanceinstance.oc1..xxxxxxEXAMPLExxxxxx"
         state: absent    
 
