---
- name: Get host information
  hosts: all
  gather_facts: yes
  vars:
    ovirt_auth:
      url: "https://olvm4/ovirt-engine/api"
      username: "admin@internal"
      password: "monica"

  tasks:
    - name: List running hosts
      ovirt_host_info:
        auth: "{{ ovirt_auth }}"
        state: present
        status: up
        maintenance: False
      register: host_info

    - name: Display host information
      debug:
        msg: "{{ item.name }} - CPU: {{ item.cpu.total }} MHz, Memory: {{ item.memory.total|filesizeformat }}B"
      loop: "{{ host_info.hosts }}"
