---
- name: Get host information
  hosts: all
  gather_facts: yes
  vars:
    ovirt_auth:
      url: "https://olvm4/ovirt-engine/api"
      username: "admin@internal"
      password: "monica"

  tasks:
       - name: List running hosts
         ovirt_host:
           auth: "{{ ovirt_auth }}"
           query: "status=up and maintenance=False"
           state: present
         register: host_info

       - name: Display host information
         debug:
            msg: "{{ item.name }} - CPU: {{ item.cpu_total }} MHz, Memory: {{ item.memory_total|filesizeformat }}B"
         loop: "{{ host_info.results }}"
