---
- name: Get host information
  hosts: all
  gather_facts: yes
  
  vars_files:
    - vars/ovirt_infra_vars.yml
    # Contains encrypted `engine_password` varibale using ansible-vault
    - vars/passwords.yml
    
  tasks:
    - name: List running hosts
      ovirt_host_info:
        state: present
        status: up
        maintenance: False
      register: host_info

    - name: Display host information
      debug:
        msg: "{{ item.name }} - CPU: {{ item.cpu.total }} MHz, Memory: {{ item.memory.total|filesizeformat }}B"
      loop: "{{ host_info.hosts }}"
