---
- name: Preparing the hosts for leapp Upgrade
  hosts: all
  become: yes  # Enable privilege escalation
  vars_files:
    - vars/defaults.yml
    - vars/vars.yml

  tasks:

    - name: Display current release
      ansible.builtin.shell: |
        cat /etc/oracle-release
        uname -r
      register: system_info

    - name: Print current release and kernel
      ansible.builtin.debug:
        var: system_info.stdout_lines
        
    - name: Append proxy configuration to yum.conf
      blockinfile:
        path: /etc/yum.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Proxy Configuration"
        block: |
          {% if proxy != "no" %}
          proxy={{ proxy }}
          {% endif %}
          
    - name: Install mokutil
      become: yes
      yum:
       name: mokutil
       state: present

    - name: Install yum versionlock plugin
      become: yes
      yum:
       name: yum-plugin-versionlock
       state: present
       
    - name: Check Secure Boot status
      command: mokutil --sb-state
      register: secure_boot_output
      changed_when: false
      ignore_errors: true

    - name: Disable Secure Boot if enabled
      command: mokutil --disable-validation
      when: "'enabled' in secure_boot_output.stdout"
      changed_when: true

    - name: Display status after attempting to disable Secure Boot
      debug:
        msg: "Secure Boot status: {{ 'disabled' if 'enabled' in secure_boot_output.stdout else 'already disabled' }}"

    - name: Set locale using localectl
      command: localectl set-locale LANG=en_US.UTF-8


    - name: Clear version locks using yum
      command: yum versionlock clear

    - name: Performing update
      command: yum update -y

    - name: Enable repository if not already enabled
      ansible.builtin.yum_repository:
           name: ol7_leapp
           state: present
           baseurl: http://yum.oracle.com/repo/OracleLinux/OL7/leapp/x86_64
           description: Leapp Upgrade Repo
      

    - name: Install Leapp
      become: yes
      yum:
       name: leapp-upgrade
       state: present

    - name: Permit root login via ssh
      block:
        - name: Configure sshd
          lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^PermitRootLogin'
            line: PermitRootLogin yes
          register: permit_root_login

    - name: Remediation for KM note 2820209.1
      ansible.builtin.command: >
        sudo sed -i "/^enabled=0.*/a proxy={{ proxy }}" /etc/yum.repos.d/leapp-upgrade-repos-ol8.repo

    - name: Reboot system
      reboot:
         reboot_timeout: 300
     






      

        



    

        

     
