---
- name: Leapp Preupgrade stage
  hosts: all
  become: yes
  vars_files:
    - vars/defaults.yml
    - vars/vars.yml
  vars:    
     leapp_switch: "{{ leapp_switch | default('--oraclelinux') }}"

  tasks:
       
     - name: Run leapp upgrade
       ansible.builtin.shell: >
          leapp upgrade --oci  2>&1; 
       register: leapp_result
       failed_when: leapp_result.rc != 0
       changed_when: false
       ignore_errors: yes
       
