---
- name: Leapp Preupgrade stage
  hosts: all
  become: yes
  vars_files:
    - vars/defaults.yml
    - vars/vars.yml
    
- name: Run leapp pre upgrade
  hosts: all
  become: yes
  become_method: sudo
  vars:
    leapp_switch: "{{ leapp_switch | default('--oraclelinux') }}"

  tasks:
     - name: Run leapp pre upgrade
       ansible.builtin.shell: >
          set -o pipefail && leapp preupgrade --oraclelinux >/dev/null 2>&1; exit $?
       register: leapp_result
       failed_when: leapp_result.rc != 0
       changed_when: false
       ignore_errors: yes
       
     - name: Print lines 
       ansible.builtin.shell: grep -i -A5 "Risk Factor" /var/log/leapp/leapp-report.txt
       register: risk_factor_lines

     - name: Display lines 
       ansible.builtin.debug:
          var: risk_factor_lines.stdout_lines

      
