---
- name: Leapp Preupgrade stage
  hosts: all
  become: yes
  vars_files:
    - vars/defaults.yml
    - vars/vars.yml
    
- name: Run leapp pre upgrade
  hosts: all
  become: yes
  become_method: sudo
  vars:
    leapp_switch: "{{ leapp_switch | default('--oraclelinux') }}"

  tasks:
     - name: Run leapp pre upgrade
       ansible.builtin.shell: >
          set -o pipefail && leapp preupgrade --oraclelinux >/dev/null 2>&1; exit $?
       register: leapp_result
       failed_when: leapp_result.rc != 0
       changed_when: false
       ignore_errors: yes

- name: Search for "Risk Factor: high" in leapp-report
  hosts: all
  gather_facts: false

  tasks:
    - name: Read leapp-report file
      ansible.builtin.shell: cat /var/log/leapp/leapp-report.txt
      register: leapp_report_content

    - name: Extract lines with "Risk Factor: high"
      ansible.builtin.set_fact:
        risk_factor_lines: "{{ leapp_report_content.stdout_lines | select('search', 'Risk Factor: high') | list }}"

    - name: Print lines with "Risk Factor: high"
      ansible.builtin.debug:
        var: risk_factor_lines

      
