---
- name: Preparing the hosts for leapp Upgrade
  hosts: all
  become: yes  # Enable privilege escalation

  tasks:

    - name: Install mokutil
      become: yes
      yum:
       name: mokutil
       state: present
       
    - name: Check Secure Boot status
      command: mokutil --sb-state
      register: secure_boot_output
      changed_when: false
      ignore_errors: true

    - name: Disable Secure Boot if enabled
      command: mokutil --disable-validation
      when: "'enabled' in secure_boot_output.stdout"
      changed_when: true

    - name: Display status after attempting to disable Secure Boot
      debug:
        msg: "Secure Boot status: {{ 'disabled' if 'enabled' in secure_boot_output.stdout else 'already disabled' }}"

    - name: Set locale using localectl
      command: localectl set-locale LANG=en_US.UTF-8


    - name: Clear version locks using yum
      command: yum versionlock clear


    

        

     
