---
- name: Leapp Preupgrade stage
  hosts: all
  become: yes
  vars_files:
    - vars/defaults.yml
    - vars/vars.yml
    
- name: Run leapp pre upgrade
  hosts: all
  become: yes
  become_method: sudo
  vars:
    leapp_switch: "{{ leapp_switch | default('--oraclelinux') }}"

  tasks:
     - name: Run leapp pre upgrade
       ansible.builtin.command: >
          set -o pipefail && leapp preupgrade --oraclelinux >/dev/null 2>&1
       register: leapp_output
       failed_when: leapp_output.rc != 0
       changed_when: false


- name: Search for Risk Factors
  hosts: all
  gather_facts: false

  tasks:
    - name: Read leapp-report file
      ansible.builtin.slurp:
        path: /var/log/leapp/leapp-report.txt  # Replace with the actual path to your leapp-report file
      register: leapp_report_content

    - name: Split content 
      ansible.builtin.set_fact:
        risk_factor_sections: "{{ leapp_report_content.content | b64decode | ansible.builtin.regex_findall('(Risk Factor: high \\(inhibitor\\)[\\s\\S]*?)(?=Risk Factor: high \\(inhibitor\\)|$)') }}"

    - name: Print Risk Factor
      ansible.builtin.debug:
        var: risk_factor_sections
      
