---
- name: Leapp Preupgrade stage
  hosts: all
  become: yes
  vars_files:
    - vars/defaults.yml
    - vars/vars.yml
    
- name: Run leapp pre upgrade
  hosts: all
  become: yes
  become_method: sudo
  vars:
    leapp_switch: "{{ leapp_switch | default('--oraclelinux') }}"

  tasks:
    - name: Run leapp pre upgrade
      command: leapp preupgrade {{ leapp_switch }}
      
