---
- name: List VMs in OLVM using environment variables
  hosts: localhost
  gather_facts: false
  tasks:

    - name: List OLVM VM's {{ vm_name }} by Cluster {{ olvm_cluster }}
      ovirt_vm_info:
        auth:
          url: "{{ lookup('env', 'OVIRT_URL') }}"
          username: "{{ lookup('env', 'OVIRT_USERNAME') }}"
          password: "{{ lookup('env', 'OVIRT_PASSWORD') }}"
          ca_file: "{{ olvm_cafile | default(omit) }}"
          insecure: "{{ olvm_insecure | default(true) }}"
      register: result

    - name: Print out {{ vm_name }} VM information
      debug:
        msg: "{{ result.ovirt_vms }}"
