---
- name: Main Playbook
  hosts: odscshe-pr.in.oracle.com
  vars_files:
    - password.yaml
  tasks:
    - name: Obtain SSO token with using username/password credentials
      ovirt_auth:
        url: https://odscshe-pr.in.oracle.com/ovirt-engine/api
        username: admin@internal
        ca_file: /etc/pki/ovirt-engine/ca.pem
        password: "{{ olvm_password }}"
    - ovirt.ovirt.ovirt_host_info:
        auth: "{{ ovirt_auth }}"
        fetch_nested: true
        nested_attributes:
          - reported_devices
      register: host_info

    - name: Show link layer info (MAC, Speed, Driver)
      debug:
        msg: |
          Host: {{ item.name }}
          {% for dev in item.reported_devices %}
            Interface: {{ dev.name }}
            MAC: {{ dev.mac.address }}
            Speed: {{ dev.speed | default('N/A') }}
            Driver: {{ dev.driver | default('N/A') }}
            Description: {{ dev.description | default('N/A') }}
          {% endfor %}
      loop: "{{ host_info.ovirt_hosts }}"

     
    - name: Cleanup OLVM auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
      register: host_info

  


 
