---
- name: Main Playbook
  hosts: localhost

  tasks:
    - name: Gather information from LLDP
      community.general.lldp:

    - name: Print each switch/port
      ansible.builtin.debug:
        msg: "{{ lldp[item]['chassis']['name'] }} / {{ lldp[item]['port']['ifname'] }}"
      with_items: "{{ lldp.keys() }}"


  


 
