---
- name: Main Playbook
  hosts: odscshe-pr.in.oracle.com
  vars_files:
    - password.yaml
  tasks:
    - name: Obtain SSO token with using username/password credentials
      ovirt_auth:
        url: https://odscshe-pr.in.oracle.com/ovirt-engine/api
        username: admin@internal
        ca_file: /etc/pki/ovirt-engine/ca.pem
        password: "{{ olvm_password }}"
    - ovirt.ovirt.ovirt_host_info:
        auth: "{{ ovirt_auth }}"
        fetch_nested: true
        nested_attributes:
          - reported_devices
      register: host_info

    - name: Display full reported_devices info
      ansible.builtin.debug:
        var: item.reported_devices
      loop: "{{ host_info.ovirt_hosts }}"
     
    - name: Cleanup OLVM auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
      register: host_info

  


 
