---
- name: Gather LLDP Neighbor Info from KVM hosts
  hosts: all
  become: true
  gather_facts: no

  tasks:


    - name: Get LLDP neighbors in JSON format
      command: /usr/sbin/lldpcli show neighbors -f json
      register: lldp_neighbors
      changed_when: false

    - name: Show LLDP neighbor raw info
      debug:
        var: lldp_neighbors.stdout
