- name: List User Details
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  tasks:
   - name: List users
     oci_identity_user_facts:
        user_id: "ocid1.user.oc1..aaaaaaaazhxulqtfcwym3zyplc6eelc26iudpfdi4iagfh5w6p5zrfw7q3cq"
     register: output
   - name: Print compartment details
     debug:
        msg: "{{ output }}"
