- name: List User Details
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  tasks:
   - name: List users
     oci_identity_user_facts:
        compartment_id: "ocid1.compartment.oc1..aaaaaaaazxd6wrvcuicrgbi6cbaob4pyrr3i7i33xudheqhx6pbcesobdazq"
     register: output
   - name: Print compartment details
     debug:
        msg: "{{ output }}"
