- name: List Compartment Details
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  tasks:
    - name: Get a specific compartment
      oci_identity_compartment_facts:
        compartment_id: "{{ instance_compartment }}"
      register: output
    - name: Print compartment details
      debug:
        msg: "{{ output }}"

    - name: List instances
      oci_compute_instance_facts:
        compartment_id: "{{ instance_compartment }}"
      register: instances

    - name: Print Instances
      debug:
        msg: "{{ instances }}"

    
    - name: List vcns
      oci_network_vcn_facts:
         compartment_id: "{{ instance_compartment }}"
      register: vnc

    - name: Print VCN
      debug:
        msg: "{{ vcn }}"    
