- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no

  vars_files:
    - default_vars.yml

  tasks:

      - name: Login to OLVM manager
        ovirt_auth:
          url: "{{ lookup('env', 'OVIRT_URL') }}"
          username: "{{ lookup('env', 'OVIRT_USERNAME') }}"
          password: "{{ lookup('env', 'OVIRT_PASSWORD') }}"
          ca_file: "{{ olvm_cafile | default('/etc/pki/ovirt-engine/ca.pem') }}"
          insecure: "{{ olvm_insecure | default(true) }}"
        tags:
          - always
          

      - name: Get number of KVM hosts
        ovirt_host_info:
          auth: "{{ ovirt_auth }}"
          fetch_nested: true
          nested_attributes:
                - events
                - cpu
                - hardware_information
        register: hosts_info

      - name: Get events
        ovirt_event_info:
          auth: "{{ ovirt_auth }}"
        register: events_info
    
      - name: Get number of storage domains
        ovirt_storage_domain_info:
          auth: "{{ ovirt_auth }}"
          fetch_nested: true
        register: storage_domains_info
    
      - name: Get number of VMs
        ovirt_vm_info:
          auth: "{{ ovirt_auth }}"
          fetch_nested: true
        register: vms_info
    
      - name: Get number of clusters
        ovirt_cluster_info:
          auth: "{{ ovirt_auth }}"
          fetch_nested: true
        register: clusters_info
    
      - name: Get number of templates
        ovirt_template_info:
          auth: "{{ ovirt_auth }}"
          fetch_nested: true
        register: templates_info
    
      - name: Get number of hosts in maintenance state
        set_fact:
          hosts_in_maintenance: "{{ hosts_info.ovirt_hosts | selectattr('status', 'equalto', 'maintenance') | list | length }}"
    
      - name: Get number of hosts in non responsive state
        set_fact:
          hosts_non_responsive: "{{ hosts_info.ovirt_hosts | selectattr('status', 'equalto', 'non_responsive') | list | length }}"
    
      - name: Get number of hosts in non operational state
        set_fact:
          hosts_non_operational: "{{ hosts_info.ovirt_hosts | selectattr('status', 'equalto', 'non_operational') | list | length }}"

      - name: Count active and inactive VMs
        set_fact:
          active_vms: "{{ vms_info.ovirt_vms | selectattr('status', 'equalto', 'up') | list | length }}"
          inactive_vms: "{{ vms_info.ovirt_vms | selectattr('status', 'equalto', 'down') | list | length }}"
    
      - name: Get clusters with compatibility version 4.7
        set_fact:
          clusters_47: "{{ clusters_info.ovirt_clusters | selectattr('version.major', 'equalto', 4) | selectattr('version.minor', 'equalto', 7) | list }}"

      - name: Debug host.cpu
        debug:
          msg: "{{ hosts_info }}"

      - name: Print latest 3 events with severity error
        debug:
          msg: "{{ item.description }} - {{ item.time }}"
        loop: "{{ (events_info.ovirt_events | selectattr('severity', 'equalto', 'error') | sort(attribute='time', reverse=True) | list)[:3] }}"
        when: events_info.ovirt_events | selectattr('severity', 'equalto', 'error') | list | length > 0
  
    
      - name: Generate HTML report
        template:
          src: templates/report.html.j2
          dest: /etc/pki/ca-trust/report.html
          mode: '0644'
        vars:
          hosts_info: "{{ hosts_info }}"
          storage_domains_info: "{{ storage_domains_info }}"
          vms_info: "{{ vms_info }}"
          clusters_info: "{{ clusters_info }}"
          templates_info: "{{ templates_info }}"
          hosts_in_maintenance: "{{ hosts_in_maintenance }}"
          hosts_non_responsive: "{{ hosts_non_responsive }}"
          hosts_non_operational: "{{ hosts_non_operational }}"
          clusters_47: "{{ clusters_47 }}"
          active_vms: "{{ active_vms }}"
          inactive_vms: "{{ inactive_vms }}"

    
      - name: Logout from OLVM
        ovirt_auth:
          state: absent
          ovirt_auth: "{{ ovirt_auth }}"
