- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  vars_files:
    - default_vars.yml
  tasks:
    - name: Login to OLVM manager
      ovirt_auth:
        url: "{{ lookup('env', 'OVIRT_URL') }}"
        username: "{{ lookup('env', 'OVIRT_USERNAME') }}"
        password: "{{ lookup('env', 'OVIRT_PASSWORD') }}"
        ca_file: "{{ olvm_cafile | default('/etc/pki/ovirt-engine/ca.pem') }}"
        insecure: "{{ olvm_insecure | default(true) }}"
      tags:
        - always

    # Gather KVM hosts with all network-relevant attributes
    - name: Get number of KVM hosts
      ovirt_host_info:
        auth: "{{ ovirt_auth }}"
        fetch_nested: true
        nested_attributes:
          - events
          - cpu
          - hardware_information
          - os
          - kdump_status
          - selinux
          - version
          - nics
          - bonds
          - network_attachments
      register: hosts_info

    - name: Get events
      ovirt_event_info:
        auth: "{{ ovirt_auth }}"
      register: events_info

    - name: Get number of storage domains
      ovirt_storage_domain_info:
        auth: "{{ ovirt_auth }}"
        fetch_nested: true
        nested_attributes:
          - data_center
      register: storage_domains_info

    # All logical networks with full details; includes VLAN, usages, provider, etc.
    - name: Gather all networks
      ovirt_network_info:
        auth: "{{ ovirt_auth }}"
        fetch_nested: true
        nested_attributes:
          - data_center
          - vlan
          - usages
          - mtu
          - external_provider
      register: networks_info

    - name: debug
      debug:
         var: networks_info.ovirt_networks

    - name: Get number of VMs
      ovirt_vm_info:
        auth: "{{ ovirt_auth }}"
        fetch_nested: true
      register: vms_info

    - name: Get number of clusters
      ovirt_cluster_info:
        auth: "{{ ovirt_auth }}"
        fetch_nested: true
        nested_attributes: [ networks ]
      register: clusters_info

    - name: Get number of templates
      ovirt_template_info:
        auth: "{{ ovirt_auth }}"
        fetch_nested: true
      register: templates_info

    - name: Gather all datacenters
      ovirt_datacenter_info:
        auth: "{{ ovirt_auth }}"
      register: datacenters_info 

    #####################
    # NETWORK ANALYTICS #
    #####################
    - name: Set external networks list (with provider)
      set_fact:
        external_networks: >-
          {{
            networks_info.ovirt_networks
            | selectattr('external_provider', 'defined')
            | selectattr('external_provider', '!=', None)
            | list
          }}

    - name: Set orphan (unmanaged) networks list
      set_fact:
        orphan_networks: >-
          {{
            networks_info.ovirt_networks
            | rejectattr('data_center', 'defined')
            | list
          }}

    # Generate lists and counts for hosts states
    - name: Get number and names of hosts in maintenance state
      set_fact:
        hosts_in_maintenance: "{{ hosts_info.ovirt_hosts | selectattr('status', 'equalto', 'maintenance') | list | length }}"
        hosts_maintenance_list: "{{ hosts_info.ovirt_hosts | selectattr('status', 'equalto', 'maintenance') | map(attribute='name') | list }}"

    - name: Get number and names of hosts in non responsive state
      set_fact:
        hosts_non_responsive: "{{ hosts_info.ovirt_hosts | selectattr('status', 'equalto', 'non_responsive') | list | length }}"
        hosts_non_responsive_list: "{{ hosts_info.ovirt_hosts | selectattr('status', 'equalto', 'non_responsive') | map(attribute='name') | list }}"

    - name: Get number and names of hosts in non operational state
      set_fact:
        hosts_non_operational: "{{ hosts_info.ovirt_hosts | selectattr('status', 'equalto', 'non_operational') | list | length }}"
        hosts_non_operational_list: "{{ hosts_info.ovirt_hosts | selectattr('status', 'equalto', 'non_operational') | map(attribute='name') | list }}"

    # Storage domains names
    - name: List names of storage domains
      set_fact:
        storage_domains_list: "{{ storage_domains_info.ovirt_storage_domains | map(attribute='name') | list }}"

    # Clusters names
    - name: List names of clusters
      set_fact:
        clusters_list: "{{ clusters_info.ovirt_clusters | map(attribute='name') | list }}"

    # Templates names
    - name: List names of templates
      set_fact:
        templates_list: "{{ templates_info.ovirt_templates | map(attribute='name') | list }}"

    # VM counts and name lists
    - name: Count active and inactive VMs and list their names
      set_fact:
        active_vms: "{{ vms_info.ovirt_vms | selectattr('status', 'equalto', 'up') | list | length }}"
        inactive_vms: "{{ vms_info.ovirt_vms | selectattr('status', 'equalto', 'down') | list | length }}"
        active_vms_list: "{{ vms_info.ovirt_vms | selectattr('status', 'equalto', 'up') | map(attribute='name') | list }}"
        inactive_vms_list: "{{ vms_info.ovirt_vms | selectattr('status', 'equalto', 'down') | map(attribute='name') | list }}"
        vms_list: "{{ vms_info.ovirt_vms | map(attribute='name') | list }}"

    - name: List VMs with HA enabled
      set_fact:
        ha_enabled_vms_list: >-
          {{
            vms_info.ovirt_vms
            | selectattr('high_availability.enabled', 'defined')
            | selectattr('high_availability.enabled', 'equalto', true)
            | map(attribute='name')
            | list
          }}

    - name: Get VMs with OS "Oracle Linux 8.x"
      set_fact:
        oracle_linux_8_vms_list: >-
          {{ vms_info.ovirt_vms
             | selectattr('os.type', 'defined')
             | selectattr('os.type', 'match', '(?i)oracle linux 8\\.x')
             | map(attribute='name')
             | list }}

    # Clusters 4.7 compatibility
    - name: Get clusters with compatibility version 4.7
      set_fact:
        clusters_47: "{{ clusters_info.ovirt_clusters | selectattr('version.major', 'equalto', 4) | selectattr('version.minor', 'equalto', 7) | list }}"

    - name: Detect if deployment is Self Hosted Engine
      set_fact:
        self_hosted_engine: "{{ 'HostedEngine' in (vms_info.ovirt_vms | map(attribute='name') | list) }}"

    - name: Get OLVM Engine version with rpm
      command: "rpm -q --qf '%{VERSION}-%{RELEASE}\\n' ovirt-engine"
      register: olvm_version
      changed_when: false
      become: yes

    - name: Set OLVM version fact
      set_fact:
        olvm_version: "{{ olvm_version.stdout }}"

    - name: Get number of VMs created in the last 30 days
      set_fact:
        vms_created_last_month: "{{ vms_info.ovirt_vms | selectattr('creation_time', '>=', (lookup('pipe', 'date -d \"30 days ago\" +%Y-%m-%d'))) | list | length }}"

    - name: Get list of VMs created in the last 30 days
      set_fact:
        vms_created_last_month_list: >-
          {{
            vms_info.ovirt_vms
            | selectattr('creation_time', '>=', (lookup('pipe', 'date -d "30 days ago" +%Y-%m-%d')))
            | map(attribute='name')
            | list
          }}

    - name: Build datacenter_id_to_name mapping
      set_fact:
        datacenter_id_to_name: >-
          {{
             dict(
                datacenters_info.ovirt_datacenters | selectattr('id', 'defined') | map(attribute='id') | zip(
                  datacenters_info.ovirt_datacenters | selectattr('name', 'defined') | map(attribute='name')
                )
             )
          }}

    - name: Map cluster ID to host count
      set_fact:
        cluster_id_to_host_count: >-
          {{
            dict(
              hosts_info.ovirt_hosts
              | selectattr('cluster', 'defined')
              | selectattr('cluster.id', 'defined')
              | map(attribute='cluster.id')
              | list
              | unique
              | zip(
                  hosts_info.ovirt_hosts
                  | selectattr('cluster', 'defined')
                  | selectattr('cluster.id', 'defined')
                  | groupby('cluster.id')
                  | map('last')
                  | map('length')
              )
            )
          }}

    - name: Map cluster ID to VM count
      set_fact:
        cluster_id_to_vm_count: >-
          {{
            dict(
              vms_info.ovirt_vms
              | selectattr('cluster', 'defined')
              | selectattr('cluster.id', 'defined')
              | map(attribute='cluster.id')
              | list
              | unique
              | zip(
                  vms_info.ovirt_vms
                  | selectattr('cluster', 'defined')
                  | selectattr('cluster.id', 'defined')
                  | groupby('cluster.id')
                  | map('last')
                  | map('length')
              )
            )
          }}


    - debug:
        msg: "Hosts: {{ hosts_info.ovirt_hosts }}"
    - debug:
        msg: "VMs: {{ vms_info.ovirt_vms }}"
     
    - name: Generate HTML report
      template:
        src: templates/report.html.j2
        dest: /etc/pki/ca-trust/report.html
        mode: '0644'
      vars:
        hosts_info: "{{ hosts_info }}"
        storage_domains_info: "{{ storage_domains_info }}"
        vms_info: "{{ vms_info }}"
        clusters_info: "{{ clusters_info }}"
        templates_info: "{{ templates_info }}"
        networks_info: "{{ networks_info }}"
        external_networks: "{{ external_networks }}"
        orphan_networks: "{{ orphan_networks }}"
        hosts_in_maintenance: "{{ hosts_in_maintenance }}"
        hosts_maintenance_list: "{{ hosts_maintenance_list }}"
        hosts_non_responsive: "{{ hosts_non_responsive }}"
        hosts_non_responsive_list: "{{ hosts_non_responsive_list }}"
        hosts_non_operational: "{{ hosts_non_operational }}"
        hosts_non_operational_list: "{{ hosts_non_operational_list }}"
        storage_domains_list: "{{ storage_domains_list }}"
        clusters_list: "{{ clusters_list }}"
        templates_list: "{{ templates_list }}"
        vms_list: "{{ vms_list }}"
        active_vms: "{{ active_vms }}"
        inactive_vms: "{{ inactive_vms }}"
        active_vms_list: "{{ active_vms_list }}"
        inactive_vms_list: "{{ inactive_vms_list }}"
        clusters_47: "{{ clusters_47 }}"
        vms_created_last_month: "{{ vms_created_last_month }}"
        self_hosted_engine: "{{ self_hosted_engine }}"
        olvm_version: "{{ olvm_version }}"
        datacenter_id_to_name: "{{ datacenter_id_to_name }}"
        ha_enabled_vms_list: "{{ ha_enabled_vms_list }}"
        vms_created_last_month_list: "{{ vms_created_last_month_list }}"
        oracle_linux_8_vms_list: "{{ oracle_linux_8_vms_list }}"
        cluster_id_to_host_count: "{{ cluster_id_to_host_count }}"
        cluster_id_to_vm_count: "{{ cluster_id_to_vm_count }}"
        
    - name: Logout from OLVM
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
