- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no

  vars_files:
    - default_vars.yml

  tasks:

  - name: Login to OLVM manager
    ovirt_auth:
        url: "{{ lookup('env', 'OVIRT_URL') }}"
        username: "{{ lookup('env', 'OVIRT_USERNAME') }}"
        password: "{{ lookup('env', 'OVIRT_PASSWORD') }}"
        ca_file: "{{ olvm_cafile | default('/etc/pki/ovirt-engine/ca.pem') }}"
        insecure: "{{ olvm_insecure | default(true) }}"
    tags:
        - always


  - name: Get number of KVM hosts
    ovirt_host_info:
      auth: "{{ ovirt_auth }}"
      fetch_nested: true
    register: hosts_info

  - name: Get number of storage domains
    ovirt_storage_domain_info:
      auth: "{{ ovirt_auth }}"
      fetch_nested: true
    register: storage_domains_info

  - name: Get number of VMs
    ovirt_vm_info:
      auth: "{{ ovirt_auth }}"
      fetch_nested: true
    register: vms_info

  - name: Generate HTML report
    template:
      src: templates/report.html.j2
      dest: /etc/pki/ca-trust/report.html
      mode: '0644'  
    vars:
      num_hosts: "{{ hosts_info.ovirt_hosts | length }}"
      num_storage_domains: "{{ storage_domains_info.ovirt_storage_domains | length }}"
      num_vms: "{{ vms_info.ovirt_vms | length }}"
      hosts_info: "{{ hosts_info }}"
      storage_domains_info: "{{ storage_domains_info }}"
      vms_info: "{{ vms_info }}"

  - name: Fetch HTML report
    fetch:
      src: /etc/pki/ca-trust/report.html
      dest: /etc/pki/ca-trust/report.html
      flat: yes

  - name: Logout from OLVM
    ovirt_auth:
      state: absent
      ovirt_auth: "{{ ovirt_auth }}"
    
