- hosts: all
  become: yes
  collections:
      - oracle.oci
  tasks:

      - name: List available profile
        oracle.oci.oci_os_management_hub_profile_facts:
          profile_id: "{{ profile_id }}"

      - name: List available instances
        oracle.oci.oci_os_management_hub_managed_instance:
          managed_instance_id: "{{ instance_id }}"
          state: absent

      - name: List Updates
        oracle.oci.oci_os_management_hub_available_package_facts:
           managed_instance_id: "{{ instance_id }}"



