---
- name: oVirt infra
  hosts: all
  gather_facts: false

  vars_files:
    # Contains encrypted `engine_password` varibale using ansible-vault
    - passwords.yml

  vars:
    engine_fqdn: olvm4
    engine_user: admin@internal
    engine_cafile: /etc/pki/ovirt-engine/ca.pem

    debug_vm_create: true
    db_vm:
      state: running
      cluster: Default
      template: ol9
      memory: 1GiB
      memory_max: 2GiB
      cores: 1
      tag:
        - db
        - dbvm
      disks:
        - size: 1GiB
          name: data
          storage_domain: data
          interface: virtio

    vms:
      - name: ol9
        memory: 2GiB
        cloud_init:
          host_name: ol9
          root_password: 'mypassword'
        profile: "{{ db_vm }}"
        tag:
          - pgsql
          - httpd
          
      - name: ol9_1
        memory: 2GiB
        cloud_init:
          host_name: ol9
          root_password: 'mypassword'
        profile: "{{ db_vm }}"
       

  roles:
    - vm_infra
  collections:
    - ovirt.ovirt
