---
- name: oVirt image template
  hosts: all
  gather_facts: false

  vars_files:
    # Contains encrypted `engine_password` varibale using ansible-vault
    - passwords.yml

  vars:
    engine_fqdn: olvm4
    engine_user: admin@internal
    engine_cafile: /etc/pki/ovirt-engine/ca.pem
    qcow_url: https://yum.oracle.com/templates/OracleLinux/OL9/u1/x86_64/OL9U1_x86_64-olvm-b158.ova
    # qcow_url: file:///tmp/CentOS-7-x86_64-GenericCloud.qcow2
    template_cluster: Default
    template_name: ol9
    template_memory: 2GiB
    template_cpu: 2
    template_disk_size: 10GiB
    template_disk_storage: data
    template_seal: no
  roles:
    - image_template
  collections:
    - ovirt.ovirt
