---
- name: oVirt infra
  hosts: 10.0.10.208
  gather_facts: false

  vars_files:
    - vars/ovirt_infra_vars.yml
    # Contains encrypted `engine_password` varibale using ansible-vault
    - vars/passwords.yml

  roles:
    - infra
  collections:
    - ovirt.ovirt
