---
- name: Preparing the hosts for leapp Upgrade
  hosts: all
  become: yes  # Enable privilege escalation

  tasks:
      - name: Fetch files from remote host using fetch
        ansible.builtin.fetch:
         src: "/var/log/leapp/leapp-report.txt"
         dest: "/tmp/"
         flat: yes
