---
- name: Leapp Upgrade stage
  hosts: all
  become: yes
  vars_files:
    - vars/defaults.yml
    - vars/vars.yml
  vars:    
     leapp_switch: "{{ leapp_switch | default('--oraclelinux') }}"

  tasks:
     - name: Run leapp upgrade
       ansible.builtin.shell: >
           leapp upgrade --oraclelinux 
       register: leapp_result
       failed_when: leapp_result.rc != 0
       changed_when: false

     - name: Reboot system
       reboot:
         reboot_timeout: 300

       
       
